Repository spsanderson/RandomWalker, pull requests merged in 2024-08, with the labels that each got.

#56 Development
  R/gen-brown-motion-geometric.R
  R/gen-brown-motion.R
  R/gen-discrete-walk.R
  R/gen-random-normal-walk-drift.R
Labels: enhancement

#58 Development
  R/00_global_variables.R
  R/gen-brown-motion-geometric.R
  R/gen-brown-motion.R
Labels: enhancement

#59 add Antti to DESC file and update site
  DESCRIPTION
  docs/404.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/getting-started.html
  docs/articles/index.html
  docs/authors.html
  docs/index.html
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/brownian_motion.html
  docs/reference/cgmean.html
  docs/reference/chmean.html
  docs/reference/ckurtosis.html
  docs/reference/cmean.html
  docs/reference/cmedian.html
  docs/reference/crange.html
  docs/reference/csd.html
  docs/reference/cskewness.html
  docs/reference/cvar.html
  docs/reference/discrete_walk.html
  docs/reference/euclidean_distance.html
  docs/reference/geometric_brownian_motion.html
  docs/reference/index.html
  docs/reference/kurtosis_vec.html
  docs/reference/rand_walk_helper.html
  docs/reference/random_normal_drift_walk.html
  docs/reference/random_normal_walk.html
  docs/reference/rw30.html
  docs/reference/rw_range.html
  docs/reference/skewness_vec.html
  docs/search.json
Labels: documentation

#60 The function for visualizing random walks and two internal helper functions to go with it
  R/internal_convert_snake_to_title_case.R
  R/internal_generate_caption.R
  R/visualize_walks.R
Labels: enhancement

#61 Development
  .Rbuildignore
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/helpers.R
  R/internal_convert_snake_to_title_case.R
  R/internal_generate_caption.R
  man/convert_snake_to_title_case.Rd
  man/generate_caption.Rd
  man/rand_walk_helper.Rd
  man/visualize_walks.Rd
Labels: enhancement

#62 update site
  _pkgdown.yml
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/Rplot001.png
  docs/reference/Rplot002.png
  docs/reference/Rplot003.png
  docs/reference/Rplot004.png
  docs/reference/convert_snake_to_title_case.html
  docs/reference/generate_caption.html
  docs/reference/index.html
  docs/reference/rand_walk_helper.html
  docs/reference/visualize_walks-1.png
  docs/reference/visualize_walks-2.png
  docs/reference/visualize_walks-3.png
  docs/reference/visualize_walks-4.png
  docs/reference/visualize_walks.html
  docs/search.json
  docs/sitemap.xml
Labels: documentation

#67 Fixes #66
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/stats-walk-summary.R
  _pkgdown.yml
  docs/authors.html
  docs/index.html
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/brownian_motion.html
  docs/reference/discrete_walk-1.png
  docs/reference/discrete_walk.html
  docs/reference/geometric_brownian_motion.html
  docs/reference/index.html
  docs/reference/random_normal_drift_walk.html
  docs/reference/random_normal_walk.html
  docs/reference/rw30.html
  docs/reference/summarise_walks.html
  docs/reference/summarize_walks.html
  docs/reference/visualize_walks.html
  docs/search.json
  docs/sitemap.xml
  man/summarize_walks.Rd
Labels: documentation, enhancement
