Repository spsanderson/RandomWalker, pull requests merged in 2024-10, with the labels that each got.

#117 Added the .interactive parameter
  R/plt-visualize-walks.R
Labels: enhancement

#118 Development
  DESCRIPTION
  NEWS.md
  docs/authors.html
  docs/index.html
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/discrete_walk-1.png
  docs/reference/libs/d3-bundle-5.16.0/d3-bundle.min.js
  docs/reference/libs/d3-lasso-0.0.5/d3-lasso.min.js
  docs/reference/libs/flatbush-4.4.0/flatbush.min.js
  docs/reference/libs/ggiraphjs-0.8.10/ggiraphjs.min.css
  docs/reference/libs/ggiraphjs-0.8.10/ggiraphjs.min.js
  docs/reference/libs/girafe-binding-0.8.10/girafe.js
  docs/reference/libs/htmlwidgets-1.6.4/htmlwidgets.js
  docs/reference/libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js
  docs/reference/visualize_walks-3.png
  docs/reference/visualize_walks.html
  docs/search.json
  man/visualize_walks.Rd
Labels: documentation

#120 Added the .pluck parameter
  R/plt-visualize-walks.R
Labels: enhancement

#121 update site
  NEWS.md
  docs/authors.html
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/discrete_walk-1.png
  docs/reference/visualize_walks-3.png
  docs/reference/visualize_walks-4.png
  docs/reference/visualize_walks.html
  docs/search.json
  man/visualize_walks.Rd
Labels: documentation

#124 Development
  NAMESPACE
  NEWS.md
  R/00_global_variables.R
  R/vec-running-quantile.R
  man/convert_snake_to_title_case.Rd
  man/generate_caption.Rd
  man/get_attributes.Rd
  man/rand_walk_helper.Rd
  man/running_quantile.Rd
  man/std_cum_max_augment.Rd
  man/std_cum_mean_augment.Rd
  man/std_cum_min_augment.Rd
  man/std_cum_prod_augment.Rd
  man/std_cum_sum_augment.Rd
Labels: enhancement

#127 towards #126
  NEWS.md
  README.Rmd
  README.md
  cran-comments.md
  man/figures/README-random_walk_visual_example-1.png
  man/running_quantile.Rd
Labels: Release

#128 Development
  CRAN-SUBMISSION
  DESCRIPTION
  NEWS.md
Labels: Release

#129 fixes for CRAN
  CRAN-SUBMISSION
  DESCRIPTION
  R/auto-rw30.R
  R/gen-brown-motion-geometric.R
  R/gen-brown-motion.R
  R/gen-discrete-walk.R
  R/gen-random-normal-walk-drift.R
  R/gen-random-normal-walk.R
  R/helpers.R
  R/plt-visualize-walks.R
  man/brownian_motion.Rd
  man/discrete_walk.Rd
  man/geometric_brownian_motion.Rd
  man/random_normal_drift_walk.Rd
  man/random_normal_walk.Rd
  man/rw30.Rd
  man/visualize_walks.Rd
Labels: Release

#130 git hub release
  CRAN-SUBMISSION
  NEWS.md
Labels: Release

#131 Development
  DESCRIPTION
  NEWS.md
  docs/404.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/articles/getting-started.html
  docs/articles/index.html
  docs/authors.html
  docs/index.html
  docs/news/index.html
  docs/pkgdown.yml
  docs/reference/brownian_motion-1.png
  docs/reference/brownian_motion.html
  docs/reference/cgmean.html
  docs/reference/chmean.html
  docs/reference/ckurtosis.html
  docs/reference/cmean.html
  docs/reference/cmedian.html
  docs/reference/convert_snake_to_title_case.html
  docs/reference/crange.html
  docs/reference/csd.html
  docs/reference/cskewness.html
  docs/reference/cvar.html
  docs/reference/discrete_walk-1.png
  docs/reference/discrete_walk.html
  docs/reference/euclidean_distance.html
  docs/reference/figures/README-random_walk_visual_example-1.png
  docs/reference/generate_caption.html
  docs/reference/geometric_brownian_motion-1.png
  docs/reference/geometric_brownian_motion.html
  docs/reference/get_attributes.html
  docs/reference/index.html
  docs/reference/kurtosis_vec.html
  docs/reference/rand_walk_helper.html
  docs/reference/random_normal_drift_walk-1.png
  docs/reference/random_normal_drift_walk.html
  docs/reference/random_normal_walk-1.png
  docs/reference/random_normal_walk.html
  docs/reference/running_quantile.html
  docs/reference/rw30-1.png
  docs/reference/rw30.html
  docs/reference/rw_range.html
  docs/reference/skewness_vec.html
  docs/reference/std_cum_max_augment.html
  docs/reference/std_cum_mean_augment.html
  docs/reference/std_cum_min_augment.html
  docs/reference/std_cum_prod_augment.html
  docs/reference/std_cum_sum_augment.html
  docs/reference/summarize_walks.html
  docs/reference/visualize_walks-3.png
  docs/reference/visualize_walks-4.png
  docs/reference/visualize_walks.html
  docs/search.json
Labels: documentation
